name: create_file_tool
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/json/

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/icons/ic_file.png"
